In [41]:
import json
import pandas as pd

file_path = "prices.jsonl"

# Load the JSON data from the selected file
with open(file_path, 'r', encoding='utf-8') as file:
    data = json.load(file)

# Initialize an empty list to store the rows of our DataFrame
df_rows = []

# Process the JSON data to populate the df_rows list (similar to the previous example)
for inputted_location, restaurants in data.items():
    for restaurant_name, details in restaurants.items():
        restaurant_location = details.get('location', '')
        for item, price in details.get('menu', {}).items():
            df_rows.append({
                'restaurant_name': restaurant_name,
                'menu_item': item,
                'menu_item_price': price,
                'restaurant_location': restaurant_location,
                'inputted_location': inputted_location
            })

# Convert the list of rows into a DataFrame
df = pd.DataFrame(df_rows)

  restaurant_name                  menu_item menu_item_price  \
0        McDonald        Medium French Fries            4.69
1        McDonald                   Big Mac®            6.79
2        McDonald  10 pc. Chicken McNuggets®            6.69
3        McDonald              Filet-O-Fish®            6.39
4        McDonald        2 Cheeseburger Meal           10.99

                       restaurant_location  \
0  1330 JACKSON ST, Oakland, CA, 94612, US
1  1330 JACKSON ST, Oakland, CA, 94612, US
2  1330 JACKSON ST, Oakland, CA, 94612, US
3  1330 JACKSON ST, Oakland, CA, 94612, US
4  1330 JACKSON ST, Oakland, CA, 94612, US

                           inputted_location
0  1 Frank H. Ogawa Plaza, Oakland, CA 94612
1  1 Frank H. Ogawa Plaza, Oakland, CA 94612
2  1 Frank H. Ogawa Plaza, Oakland, CA 94612
3  1 Frank H. Ogawa Plaza, Oakland, CA 94612
4  1 Frank H. Ogawa Plaza, Oakland, CA 94612

In [45]:
df['restaurant_name'] = df['restaurant_name'].str.replace(r'_[0-9]+$', '', regex=True)

In [46]:
df

,restaurant_name,menu_item,menu_item_price,restaurant_location,inputted_location
0,McDonald,Medium French Fries,4.69,"1330 JACKSON ST, Oakland, CA, 94612, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
1,McDonald,Big Mac®,6.79,"1330 JACKSON ST, Oakland, CA, 94612, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
2,McDonald,10 pc. Chicken McNuggets®,6.69,"1330 JACKSON ST, Oakland, CA, 94612, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
3,McDonald,Filet-O-Fish®,6.39,"1330 JACKSON ST, Oakland, CA, 94612, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
4,McDonald,2 Cheeseburger Meal,10.99,"1330 JACKSON ST, Oakland, CA, 94612, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
...,...,...,...,...,...
8160,The Habit,Ranch,0.63,"5291 Martinelli Way, Dublin, CA, 94568, US","3300 Capitol Ave, Fremont, CA 94538"
8161,The Habit,BBQ Sauce,0.63,"5291 Martinelli Way, Dublin, CA, 94568, US","3300 Capitol Ave, Fremont, CA 94538"
8162,The Habit,Spicy Red Pepper Sauce,0.75,"5291 Martinelli Way, Dublin, CA, 94568, US","3300 Capitol Ave, Fremont, CA 94538"
8163,The Habit,Teriyaki Sauce,0.63,"5291 Martinelli Way, Dublin, CA, 94568, US","3300 Capitol Ave, Fremont, CA 94538"
8164,The Habit,Sweet Mustard,0.75,"5291 Martinelli Way, Dublin, CA, 94568, US","3300 Capitol Ave, Fremont, CA 94538"

In [60]:
oakland_mcdonalds_locs = df[df['inputted_location']== "1 Frank H. Ogawa Plaza, Oakland, CA 94612"]
test = oakland_mcdonalds_locs[oakland_mcdonalds_locs['restaurant_name'] == "Wendy"]
filtered_rows = test[test['menu_item'].str.contains("Dave's Combo", case=False, na=False)]
filtered_rows

,restaurant_name,menu_item,menu_item_price,restaurant_location,inputted_location
294,Wendy,Dave's Combo,0.00,"5211 Broadway, Oakland, CA, 94618, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
2116,Wendy,Dave's Combo,0.00,"3111 E. 14Th Street, Oakland, CA, 94601, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
2211,Wendy,Dave's Combo,0.00,"189 98Th Avenue, Oakland, CA, 94603, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
2308,Wendy,Dave's Combo,0.00,"1185, San Leandro, CA, 94577, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
2397,Wendy,Dave's Combo,0.00,"12201 San Pablo Avenue, Richmond, CA, 94805, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"
2494,Wendy,Dave's Combo,0.00,"17435 Hesperian Blvd, San Lorenzo, CA, 94580, US","1 Frank H. Ogawa Plaza, Oakland, CA 94612"

In [ ]:
df.to_csv('fast_food_restaurants_menu.csv', index=False)